from openai import OpenAI
import json
import os
import time

# ------------------------
# OPENROUTER FREE MODELS FALLBACK LIST
# ------------------------
FREE_MODELS = [
    "meta-llama/llama-3.3-70b-instruct:free",
    "meta-llama/llama-3.1-8b-instruct:free",
    "mistralai/mistral-7b-instruct:free",
    "google/gemma-3-12b-it:free",
    "deepseek/deepseek-r1:free",
    "qwen/qwen2.5-72b-instruct:free",
]

client = OpenAI(
    api_key=os.getenv("GROQ_API_KEY"),
    base_url="https://openrouter.ai/api/v1"
)

# ------------------------
# LOAD BUILD LOG
# ------------------------
try:
    with open("build.log", "r") as f:
        build_logs = f.read()
except:
    build_logs = None

# ------------------------
# LOAD TRIVY SCAN
# ------------------------
try:
    with open("scan.json", "r") as f:
        scan_data = json.load(f)
except:
    scan_data = None

# ------------------------
# SMART PROMPT
# ------------------------
prompt = f"""
You are a Senior DevOps + DevSecOps engineer.
You MUST analyze BOTH sections if available.

RULES:
1. Always prioritize BUILD FAILURE first if present
2. Then analyze SECURITY (Trivy CVEs)
3. If both exist, merge into a single structured report
4. Provide actionable fixes for each issue

---
BUILD FAILURE LOGS:
{build_logs if build_logs else "No build failure detected"}

---
TRIVY SECURITY SCAN:
{json.dumps(scan_data, indent=2) if scan_data else "No security issues detected"}

---
OUTPUT FORMAT:
## 🚨 Primary Issue (Build / CI Failure)
- Root cause
- Fix
- Suggested Dockerfile/code change

## ⚠️ Security Issues (CVEs)
- List HIGH/CRITICAL issues
- Risk explanation
- Fix (base image / dependency upgrade)

## 🧠 Final Recommendation
- What to fix first
- What to improve long-term
"""

# ------------------------
# CALL WITH FALLBACK
# ------------------------
def call_with_fallback(prompt, retries_per_model=2):
    for model in FREE_MODELS:
        for attempt in range(retries_per_model):
            try:
                print(f"🔄 Trying model: {model} (attempt {attempt + 1})")
                response = client.chat.completions.create(
                    model=model,
                    messages=[{"role": "user", "content": prompt}],
                    extra_headers={
                        "HTTP-Referer": "https://github.com",
                        "X-Title": "DevOps AI Analyzer"
                    }
                )
                content = response.choices[0].message.content
                print(f"✅ Success with model: {model}")
                return content, model

            except Exception as e:
                error_str = str(e)

                if "429" in error_str:
                    wait = (attempt + 1) * 20
                    print(f"⏳ Rate limited on {model}. Waiting {wait}s...")
                    time.sleep(wait)

                elif "402" in error_str:
                    print(f"❌ Credits issue on {model}. Skipping...")
                    break

                elif "503" in error_str or "502" in error_str:
                    print(f"⚠️ Model {model} unavailable. Trying next...")
                    break

                else:
                    print(f"❌ Unknown error on {model}: {e}")
                    break

    raise Exception("❌ All free models failed. Check OpenRouter status.")


# ------------------------
# RUN
# ------------------------
result, used_model = call_with_fallback(prompt)

# ------------------------
# SAVE OUTPUT
# ------------------------
report = f"""# 🤖 Auto-Healing Report
> Generated by: `{used_model}`

---

{result}
"""

with open("auto_healing_report.md", "w") as f:
    f.write(report)

print("✅ Auto-healing report generated successfully")
print(f"📄 Report saved to: auto_healing_report.md")
print(f"🤖 Model used: {used_model}")
